---
# tasks file for common
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Add Puppet Labs Repository
  ansible.builtin.package:
    name: http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
    state: present

- name: Install Common Items
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ common_packages }}"

- name: Install Pip Packages
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items:
    - "{{ pip_packages }}"

- name: Configure Admin User
  ansible.builtin.user:
    name: "{{ admin_user }}"
    password: "{{ admin_pass }}"
    comment: admin user
    groups:
      - wheel
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  register: adminout
- debug:
    var: adminout

- name: Output Private Key
  ansible.builtin.shell:
    cmd: cat "{{ adminout.ssh_key_file }}"
  when: adminout.changed
  register: adminkey

- debug:
    var:  adminkey.stdout

- name: Configure Unpriiviledged User
  ansible.builtin.user:
    name: "{{ norm_user }}"
    password: "{{ norm_pass }}"
    comment: regular user
    groups:
      - users
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  register: normout

- name: Output Private Key
  ansible.builtin.shell:
    cmd: cat "{{ normout.ssh_key_file }}"
  when: normout.changed
  register: normkey

- debug:
    var:  normkey.stdout