---
# tasks file for common
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  become: true

- name: Install Common Items
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - "{{ common_packages }}"

- name: Install Pip Packages
  ansible.builtin.pip:
    name: "{{ item }}"
  become: true
  with_items:
    - "{{ pip_packages }}"

- name: Configure Admin User
  ansible.builtin.user:
    name: "{{ admin_user }}"
    password: "{{ admin_pass }}"
    comment: admin user
    groups:
      - wheel
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  register: adminout
  become: true

- name: Output Private Key
  ansible.builtin.shell:
    cmd: cat "{{ adminout.ssh_key_file }}"
  when: adminout.changed
  register: adminkey
  become: true

- debug:
    var:  adminkey.stdout

- name: Configure Unpriiviledged User
  become: true
  ansible.builtin.user:
    name: "{{ norm_user }}"
    password: "{{ norm_pass }}"
    comment: regular user
    groups:
      - users
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  register: normout

- name: Output Private Key
  become: true
  ansible.builtin.shell:
    cmd: cat "{{ normout.ssh_key_file }}"
  when: normout.changed
  register: normkey

- debug:
    var:  normkey.stdout

# - name: Copy Github Private Key
#   copy:
#     src: "{{ playbook_dir }}/files/gihub_rsa"
#     dest: "{{ item }}/.ssh/"
#     mode: 0600
#   with_items:
#     - "{{ userdirs }}"

# - name: Copy Github Public Key
#   copy:
#     src: "{{ playbook_dir }}/files/gihub_rsa.pub"
#     dest: "{{ item }}/.ssh/"
#     mode: 0600
#   with_items:
#     - "{{ userdirs }}"

# - name: Copy SSH Config
#   copy:
#     src: "{{ playbook_dir }}/files/ssh_config"
#     dest: "{{ item }}/.ssh/config"
#     mode: 0600
#   with_items:
#     - "{{ userdirs }}"
