---
# tasks file for foreman
- name: Install Puppet3
  ansible.builtin.expect:
    command: yay puppet3
    responses:
      (?i)Packages to install: "1"
      (?i)Remove make dependencies after install?: "Y"
      (?i)Packages to cleanBuild?: "N"
      (?i)Diffs to show?: "N"
      (?i)Proceed with installation?: "Y"
