---
# tasks file for foreman
- name: Install Foreman and Puppet Repos
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ repos }}"

- name: Install Foreman Install Helper
  ansible.builtin.package:
    name: foreman-installer
    state: present

- name: Disable Faulty Repos
  ansible.builtin.shell:
    cmd: yum-config-manager --disable "{{ item }}"
  with_items:
    - "{{ disabled_repos }}"

# - name: Run Foreman Install
#   ansible.builtin.shell: |
#      foreman-installer \
#      --foreman-admin-username="{{ admin_user }}" \
#      --foreman-admin-password="{{ admin_pass }}"
#   register: foreman_install_out

# - debug:
#     var: foreman_install_out.stdout
# - debug:
#     var: foreman_install_out.stderr
  
    